
<script type="text/javascript" src="/public/js/aplicacao/produtos/produtos.js"></script>

<div id="prod_janela" class="janela col-xs-offset-2 col-sm-offset-2 col-md-offset-1 col-lg-offset-1 col-lg-11" style="display: none" data-title="Produtos">
    <div class="divisao-janela">
        <form method="POST" action="" id="prod_form">
            <div class="modal-header">
                <button type="button" data-toggle="tooltip" data-placement="bottom" title="Fechar">
                    <i class="fa fa-close fa-1x"></i>
                </button>
                <h4 class="modal-title"><i class="fa fa-shopping-cart fa-1x"></i> Gerenciamento de Produtos</h4>
            </div>
            <div class="modal-body clearfix" style="padding-bottom: 5px;">
                
                <div id="prod_alertas" class="label label-default col-lg-12 hide"></div>

                <div class="col-lg-3">
                
                    <fieldset>
                        <legend>Fornecedores:</legend>
                        <div class="clearfix" style="margin: 7px 0;">
                            <div class="col-lg-12" >
                                <select id="prod_forn_select" class="form-control" name="fornecedor_id" data-obrigatorio > <option>Selecione...</option> </select>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset>
                        <legend class="clearfix" style="margin: 7px 0;">Produto: </legend>
                        <div class="form-group col-lg-12" >
                            <label>Marcas*</label>
                            <select id="prod_marca_select" class="form-control" name="marca_id" data-obrigatorio > <option>Selecione...</option> </select>
                        </div>
                        <div class="form-group col-lg-6">
                            <label>Localização*</label>
                            <select id="prod_veic_marca_select" class="form-control" name="veic_marca_id" data-obrigatorio > <option>Selecione...</option> </select>
                        </div>
                        <div class="form-group col-lg-6">
                            <label>Categoria*</label>
                            <input type="text" class="form-control" name="categoria" id="prod_categoria" data-obrigatorio />
                        </div>
                        <div class="form-group col-lg-12">
                            <label>Descricao*</label>
                            <input type="text" class="form-control" name="descricao" id="prod_descricao" data-obrigatorio />
                        </div>
                        <div class="form-group col-lg-4">
                            <label>Quantidade*</label>
                            <input type="text" class="form-control" name="quantidade" id="prod_quantidade" data-obrigatorio />
                        </div>
                        <div class="form-group col-lg-4">
                            <label>Unidade*</label>
                            <select id="prod_unidade" class="form-control" name="unidade" data-obrigatorio > 
                                <option value="">Selecione...</option> 
                                <option value="UNID">UNIDADE</option> 
                                <option value="METRO">METRO</option> 
                                <option value="JOGO">JOGO</option> 
                            </select>
                        </div>
                        <div class="form-group col-lg-4">
                            <label>Espessura</label>
                            <input type="text" class="form-control" name="espessura" id="prod_espessura" />
                        </div>
                        <div class="form-group col-lg-6">
                            <label>P. custo*</label>
                            <input type="text" class="form-control" name="precocusto" id="prod_precocusto" data-tipo="currency" data-obrigatorio  />
                        </div>
                        <div class="form-group col-lg-6">
                            <label>P. venda*</label>
                            <input type="text" class="form-control" name="precovenda" id="prod_precovenda" data-tipo="currency" data-obrigatorio />
                        </div>
                        <div>
                            <div class="form-group col-lg-12">
                                <label>Observações</label>
                                <textarea id="prod_obs" name="obs" class="form-control" ></textarea>
                            </div>
                        </div>
                        <div class="form-group col-lg-12 text-right">
                            <input type="checkbox" name="status" id="prod_status" checked />
                            <label>Ativo</label>
                        </div>
                    </fieldset>
                    <div class="col-lg-12 text-right" >
                        <button type="button" id="prod_desfazer" class="text-center btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Desfazer">
                            <i class="fa fa-undo fa-1x"></i>
                        </button>
                        <button class="text-center btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Confirmar">
                            <i class="fa fa-check fa-1x" style="color:#cc7a00"></i>
                        </button>
                    </div>
                    
                </div>
                <div class="col-lg-9">
                    <fieldset>
                        <legend>Produtos:</legend>
                        <div class="col-lg-12" style="margin: 7px 0; max-height:400px; overflow:auto;">
                            <table id="prod_tabela" class="table table-bordered table-condensed">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th class="col-lg-1">Marca</th>
                                        <th class="col-lg-1">Localização</th>
                                        <th class="col-lg-1">Categoria</th>
                                        <th class="">Descrição</th>
                                        <th class="col-lg-1">Quant.</th>
                                        <th class="col-lg-1">Unid.</th>
                                        <th class="col-lg-1">Esp.</th>
                                        <th class="col-lg-1">Custo</th>
                                        <th class="col-lg-1">Venda</th>
                                        <th class="col-lg-1">Status</th>
                                        <th>Obs</th>
                                        <th class="col-lg-1"><i class="fa fa-edit"></i></th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </fieldset>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="prod_modal_marca" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <form id="prod_modal_marca_form">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-close fa-1x"></i></button>
                    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-edit fa-1x"></i> Gerenciar marcas de produtos</h4>
                </div>
                <div class="modal-body clearfix">

                    <div id="prod_modal_marca_alertas" class="label label-default col-lg-12 hide"></div>

                    <div class="col-lg-12">
                        <fieldset>
                            <legend>Marcas: </legend>
                            <div class="form-group col-lg-12">
                                <label>Marca*</label>
                                <select id="prod_modal_marca_select" class="form-control" name="id" > <option>Nova...</option> </select>
                            </div>
                            <div class="form-group col-lg-12">
                                <label>Nome*</label>
                                <input type="text" class="form-control" name="nome" id="modal_prod_marca_nome" data-obrigatorio />
                            </div>
                            <div class="form-group col-lg-12 text-right">
                                <input type="checkbox" class="" name="status" id="modal_prod_marca_status" checked />
                                <label>Ativo</label>
                            </div>
                           
                        </fieldset>
                        
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="prod_modal_prod_marca_confirmar" class="text-center" data-toggle="tooltip" data-placement="bottom" title="Confirmar">
                        <i class="fa fa-check fa-1x"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="prod_modal_prod" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-l">
            <form id="prod_modal_form">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-close fa-1x"></i></button>
                    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-edit fa-1x"></i> Alterar</h4>
                </div>
                <div class="modal-body clearfix">

                    <div id="prod_modal_alertas" class="label label-default col-lg-12 hide"></div>

                    <div class="col-lg-12">
                        <fieldset>
                            <legend class="clearfix" style="margin: 7px 0;">Produto: </legend>
                            <div class="form-group col-lg-4" >
                                <label>Marca*</label>
                                <select id="modal_prod_marca_select" class="form-control" name="marca_id" data-obrigatorio > <option>Selecione...</option> </select>
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Localização*</label>
                                <select id="modal_prod_veic_select" class="form-control" name="veic_marca_id" data-obrigatorio > <option>Selecione...</option> </select>
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Categoria*</label>
                                <input type="text" class="form-control" name="categoria" id="modal_prod_categoria" data-obrigatorio />
                            </div>
                            <div class="form-group col-lg-12">
                                <label>Descricao*</label>
                                <input type="text" class="form-control" name="descricao" id="modal_prod_descricao" data-obrigatorio />
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Quantidade*</label>
                                <input type="text" class="form-control" name="quantidade" id="modal_prod_quantidade" data-obrigatorio />
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Unidade*</label>
                                <select id="modal_prod_unidade" class="form-control" name="unidade" data-obrigatorio > 
                                    <option value="">Selecione...</option> 
                                    <option value="UNID">UNIDADE</option> 
                                    <option value="METRO">METRO</option> 
                                    <option value="JOGO">JOGO</option> 
                                </select>
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Espessura</label>
                                <input type="text" class="form-control" name="espessura" id="modal_prod_espessura" />
                            </div>
                            <div class="form-group col-lg-6">
                                <label>P. custo*</label>
                                <input type="text" class="form-control" name="precocusto" id="modal_prod_precocusto" data-tipo="currency" data-obrigatorio />
                            </div>
                            <div class="form-group col-lg-6">
                                <label>P. venda*</label>
                                <input type="text" class="form-control" name="precovenda" id="modal_prod_precovenda" data-tipo="currency" data-obrigatorio />
                            </div>
                            <div>
                                <div class="form-group col-lg-12">
                                    <label>Observações</label>
                                    <textarea id="modal_prod_obs" name="obs" class="form-control" ></textarea>
                                </div>
                            </div>
                            <div class="form-group col-lg-12 text-right">
                                <input type="checkbox" name="status" id="modal_prod_status" checked />
                                <label>Ativo</label>
                            </div>
                        </fieldset>

                            <input type="hidden" class="form-control" name="id" id="modal_prod_id" />
                        </fieldset>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="prod_modal_prod_confirmar" class="text-center" data-toggle="tooltip" data-placement="bottom" title="Confirmar">
                        <i class="fa fa-check fa-1x"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>