<?php

    $os = $this->os[0];
    $os_itens = $this->os_itens;
    
    $total_itens = 0;
    
//    echo '<pre>';
//    print_r($os);
//    die();
        
?>
<style>
    @page { margin: 0; }
    
    body{
        background: transparent;
        text-transform: uppercase;
    }
    .bold { font-weight: bold; }
    .border {
        border: 1px solid #676060;
        margin: 1px;
        padding: 2px;
    }
    .lowercase { text-transform: lowercase; }

    /* BOOTSTRAP - INICIO */
    
    *:before, *:after {
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
    }
    * {
        font-family: 'Roboto', sans-serif;
        font-size: small;
        box-sizing: border-box;
    }
    .text-center { text-align: center }
    .text-right { text-align: right; }
    .text-left { text-align: left; }
    
    .col-xs-1, .col-sm-1, .col-md-1, .col-lg-1, .col-xs-2, .col-sm-2, .col-md-2, .col-lg-2, .col-xs-3, .col-sm-3, .col-md-3, .col-lg-3, .col-xs-4, .col-sm-4, .col-md-4, .col-lg-4, .col-xs-5, .col-sm-5, .col-md-5, .col-lg-5, .col-xs-6, .col-sm-6, .col-md-6, .col-lg-6, .col-xs-7, .col-sm-7, .col-md-7, .col-lg-7, .col-xs-8, .col-sm-8, .col-md-8, .col-lg-8, .col-xs-9, .col-sm-9, .col-md-9, .col-lg-9, .col-xs-10, .col-sm-10, .col-md-10, .col-lg-10, .col-xs-11, .col-sm-11, .col-md-11, .col-lg-11, .col-xs-12, .col-sm-12, .col-md-12, .col-lg-12
    { position: relative; min-height: 1px; padding-left: 5px; padding-right: 5px; }
    .col-lg-1, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-lg-10, .col-lg-11, .col-lg-12{ float: left; }
    .col-lg-1 { width: 8.33333333%; }
    .col-lg-2 { width: 16.66666667%; }
    .col-lg-3 { width: 25%; }
    .col-lg-4 { width: 33.33333333%; }
    .col-lg-5 { width: 41.66666667%; }
    .col-lg-6 { width: 50%; }
    .col-lg-8 { width: 66.66666667%; }
    .col-lg-9 { width: 75%; }
    .col-lg-12 { width: 100%; }
    table {
        border-collapse: collapse;
        border-spacing: 0;
    }
    .table {
        background: white;
        width: 100%;
        max-width: 100%;
        margin-bottom: 7px;
    }
    .table-bordered { border: 1px solid #ddd; }
 
    td, th {
        padding: 0;
    }
    th {
        text-align: center;
    }
    .table>thead>tr>th, .table>tbody>tr>th, .table>tfoot>tr>th, .table>thead>tr>td, .table>tbody>tr>td, .table>tfoot>tr>td {
        padding: 8px;
        line-height: 1.2;
        vertical-align: top;
        border-top: 1px solid #ddd;
    }
    .table>thead>tr>th {
        vertical-align: bottom;
        border-bottom: 2px solid #ddd;
    }
    .table-condensed>thead>tr>th, .table-condensed>tbody>tr>th, .table-condensed>tfoot>tr>th, .table-condensed>thead>tr>td, .table-condensed>tbody>tr>td, .table-condensed>tfoot>tr>td {
        padding: 2px;
    }
    .table-bordered>thead>tr>th, .table-bordered>tbody>tr>th, .table-bordered>tfoot>tr>th, .table-bordered>thead>tr>td, .table-bordered>tbody>tr>td, .table-bordered>tfoot>tr>td {
        border: 1px solid #ddd;
    }
    .table-bordered>thead>tr>th, .table-bordered>thead>tr>td {
        border-bottom-width: 2px;
    }
    .table>caption+thead>tr:first-child>th, .table>colgroup+thead>tr:first-child>th, .table>thead:first-child>tr:first-child>th, .table>caption+thead>tr:first-child>td, .table>colgroup+thead>tr:first-child>td, .table>thead:first-child>tr:first-child>td {
        border-top: 0;
    }
    .table-striped>tbody>tr:nth-of-type(odd) {
        background-color: #f9f9f9;
    }
    .table-bordered>thead>tr>th, .table-bordered>tbody>tr>th, .table-bordered>tfoot>tr>th, .table-bordered>thead>tr>td, .table-bordered>tbody>tr>td, .table-bordered>tfoot>tr>td {
        border: 1px solid #ddd;
    }
    .table tbody td {
        text-align: center;
        padding: 0;
        font-size: 10px;
    }

    /* BOOTSTRAP - FIM */
    
</style>

<div class="col-lg-12" id="os-main">

    <div class="col-lg-12 text-center bold border"> 
        <div class="col-lg-12" style="font-size: 8px">NAO E DOCUMENTO FISCAL - NAO E VALIDO COMO RECIBO/GARANTIA - NAO E COMPROVANTE</div>
        <div class="col-lg-12" style="font-size: 10px"><?= $os['emp_fantasia'] ?> - <?= $os['emp_endereco'] ?></div>
        <div class="col-lg-12" style="font-size: 10px">Telefone(s): <?= $os['emp_fone1'] ?> / <?= $os['emp_fone2'] ?> CNPJ: <?= $os['emp_cnpj'] ?></div>
    </div>
    
    <div class="col-lg-12 border">
        <div class="col-lg-6">
            <div class="col-lg-12 text-center bold">Cliente</div>
            <div class="col-lg-4 bold">Cliente: </div><div class="col-lg-8"><?= $os['cli_nome'] ?></div>
            <div class="col-lg-4 bold">Endereço: </div><div class="col-lg-8"><?= $os['cli_endreco'] ?></div>
            <div class="col-lg-4 bold">Telefones: </div><div class="col-lg-8"><?= $os['cli_fone1'] ?> - <?= $os['cli_fone2'] ?></div>
            <div class="col-lg-4 bold">CNPJ/CPF/RG: </div><div class="col-lg-8"><?= $os['cli_nrodocumento'] ?></div>
        </div>

        <div class="col-lg-6" style="border-left: 1px solid #ccc">
            <div class="col-lg-12 text-center bold">Veículo</div>
            <div class="col-lg-4 bold">Marca: </div><div class="col-lg-8"><?= $os['veic_marca'] ?></div>
            <div class="col-lg-4 bold">Modelo: </div><div class="col-lg-8"><?= $os['veic_modelo'] ?></div>
            <div class="col-lg-4 bold">Placa: </div><div class="col-lg-8"><?= $os['veic_placa'] ?></div>
            <div class="col-lg-4 bold">Ano: </div><div class="col-lg-8"><?= $os['veic_ano'] ?></div>
            <div class="col-lg-4 bold">Cor: </div><div class="col-lg-8"><?= $os['veic_cor'] ?></div>
            <div class="col-lg-3 bold">Obs: </div><div class="col-lg-9 lowercase"><?= $os['veic_obs'] ?></div>
        </div>
    </div>
    
    <div class="col-lg-12 border">
        
        <table class="table table-bordered table-condensed table-striped">
            <thead>
                <tr>
                    <th colspan="7" >Peças</th>
                </tr>
                <tr>
                    <th class="col-lg-1">Cód.</th> 
                    <th class="col-lg-4">Descrição</th> 
                    <th class="col-lg-1">Quant.</th> 
                    <th class="col-lg-2">Prc. Unit</th> 
                    <th class="col-lg-2">Total</th> 
                    <th class="col-lg-2">Vend.</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($os_itens as $item) : $total_itens+=$item['precototal']; ?>
                <tr>
                    <td class="col-lg-1"><?= $item['id'] ?></td>
                    <td class="col-lg-4"><?= $item['descricao'] ?></td>
                    <td class="col-lg-1"><?= $item['quant'] ?></td>
                    <td class="col-lg-2">R$ <?= $item['precovenda'] ?></td>
                    <td class="col-lg-2">R$ <?= $item['precototal'] ?></td>
                    <td class="col-lg-2"><?= $os['func_nome'] ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <table class="table table-bordered table-condensed table-striped">
            <thead>
                <tr>
                    <th colspan="5">Pagamento</th>
                </tr>
                <tr>
                    <th>Sub Total</th>
                    <th>Mão de Obra</th>
                    <th>Desconto (%)</th>
                    <th>Total</th>
                    <th>Tipo</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><?= $total_itens ?></td>
                    <td>R$ <?= $os['precomaodeobra'] ?></td>
                    <td><?= $os['percdescmaodeobra'] ?>%</td>
                    <td>R$ <?= $total_itens + $os['precomaodeobratotal'] ?></td>
                    <td><?= $os['formapagto'] ?></td>
                </tr>
            </tbody>
        </table>
        
        <div>Observações</div>
        <textarea style="width: 100%" rows="2" placeholder="Observação"><?= $os['obs'] ?></textarea>
        
        
    </div>
    
    <div class="col-lg-6 " style="border: 1px solid #000; margin: 10px 0; height: 50px; left: 25%">
        <span style="font-size: 10px">Recebemos</span>
    </div>
    
</div>

<div class="col-lg-12">
    <hr />
</div>

<div class="col-lg-12" id="os-main-copy"></div>

<script>
    $(function (){
        var os_copy = $('#os-main').html();
        $('#os-main-copy').append(os_copy)
    });
    
    print();
</script>
