<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'href' => ''))
        ->prependStylesheet($this->basePath() . 'public/css/aplicacao/index.css');

echo $this->headScript()
        ->prependFile($this->basePath() . 'public/js/aplicacao/index.js');

$this->headMeta()->appendName('keywords', 'Sistema, Agendas');
?>
<!-- Cabeçalho -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">

    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div style="color: #FF9900; margin-top: 7px" ><img src="<?= $this->basePath() . 'public/img/id-visual/logo_36.png'?>" /></div>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a style="color:#FF9900" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        <span class="fa fa-gear"></span> Cadastros <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <!--<li><a href="#" class="open-app" data-title="Pessoas"><i class="fa fa-user"></i> Pessoas</a></li>-->                             
                        <li><a href="#" class="open-app" data-title="Funcionarios"><i class="fa fa-address-card"></i> Funcionários</a></li>                             
<!--                        <li><a href="#" class="open-app" data-title="Veiculos"><i class="fa fa-car"></i> Veículos</a></li>                             -->
                        <li><a href="#" class="open-app" data-title="Produtos"><i class="fa fa-shopping-cart"></i> Produtos</a></li>                             
                        <li><a href="#" class="open-app" data-title="ProdutosMarcas"><i class="fa fa-shopping-cart"></i> Marcas de produtos</a></li>                             
                    </ul>
                </li>
            </ul>
            
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="sidebar text-center" style="width: 50px">
    <ul class="nav nav-sidebar">
        <li> <button type="button" class="btn btn-app" style="padding: 13px" data-toggle="tooltip" data-placement="right" data-title="Pessoas" title="Pessoas"><i class="fa fa-user fa-1x" aria-hidden="true"></i></button> </li>
        <li> <button type="button" class="btn btn-app" style="padding: 13px" data-toggle="tooltip" data-placement="right" data-title="Veiculos" title="Veiculos"><i class="fa fa-car fa-1x" aria-hidden="true"></i></button> </li>
    </ul>
</div>

<!-- // Cabeçalho -->

<div style="padding-top:51px; height: 100%" class="container-fluid no-padding">

    <!-- Corpo -->
    <?php echo $this->partial('telas/pessoas', ['variaveis'=>$this->telas]) ?>
    <?php echo $this->partial('telas/funcionarios', ['variaveis'=>$this->telas]) ?>
    <?php echo $this->partial('telas/veiculos', ['variaveis'=>$this->telas]) ?>
    <?php echo $this->partial('telas/aplicacao/produtos', ['variaveis'=>$this->telas]) ?>
    <?php echo $this->partial('telas/aplicacao/marcas', ['variaveis'=>$this->telas]) ?>
   
</div>
