<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'href' => ''))
        ->prependStylesheet($this->basePath() . 'public/css/aplicacao/index.css');

echo $this->headScript()
        ->prependFile($this->basePath() . 'public/js/aplicacao/index.js');

$this->headMeta()->appendName('keywords', 'Sistema, Agendas');
?>
<!-- Cabeçalho -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">

    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div style="color: #FF9900; margin-top: 7px" ><img src="<?= $this->basePath() . 'public/img/id-visual/logo_36.png'?>" /></div>
        </div>

        <style>
            
        </style>
        
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            
            <ul class="nav navbar-nav col-lg-push-2" style="position: relative">
                <li> <button type="button" class="btn btn-app" data-toggle="tooltip" data-placement="right" data-title="Financeiro" title="Financeiro"><i class="fa fa-money fa-2x" aria-hidden="true"></i><br /><span>Financeiro</span></button> </li>
                <li> <button type="button" class="btn btn-app" data-toggle="tooltip" data-placement="right" data-title="Manutencao" title="Manutenção"><i class="fa fa-wrench fa-2x" aria-hidden="true"></i><br /><span>Manutenção</span></button> </li>
                <li style="border-left: 1px solid #FF9900"> <button type="button" class="btn btn-app" data-toggle="tooltip" data-placement="right" data-title="Pessoas" title="Pessoas"><i class="fa fa-user fa-2x" aria-hidden="true"></i><br /><span>Pessoas</span></button> </li>
                <li> <button type="button" class="btn btn-app" data-toggle="tooltip" data-placement="right" data-title="Funcionarios" title="Funcionários"><i class="fa fa-address-card fa-2x" aria-hidden="true"></i><br /><span>Funcionários</span></button> </li>
                <li> <button type="button" class="btn btn-app" data-toggle="tooltip" data-placement="right" data-title="Veiculos" title="Veiculos"><i class="fa fa-car fa-2x" aria-hidden="true"></i><br /><span>Veículos</span></button> </li>
                <li> <button type="button" class="btn btn-app" data-toggle="tooltip" data-placement="right" data-title="Produtos" title="Produtos"><i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i><br /><span>Produtos</span></button> </li>
                <li> <button type="button" class="btn btn-app" data-toggle="tooltip" data-placement="right" data-title="ProdutosMarcas" title="Marcas"><i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i><br /><span>Marcas de produtos</span></button> </li>
                <li style="border-left: 1px solid #FF9900"> <button type="button" class="btn btn-app"><a href="/acesso/logout"><i class="fa fa-sign-out fa-2x" aria-hidden="true"></i><br /><span>Sair</span></a> </li></button>
            </ul>
            
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<!-- // Cabeçalho -->

<div style="padding-top:51px; height: 100%" class="container-fluid no-padding">

    <!-- Corpo -->
    <?php echo $this->partial('telas/pessoas', ['variaveis'=>$this->telas]) ?>
    <?php echo $this->partial('telas/funcionarios', ['variaveis'=>$this->telas]) ?>
    <?php echo $this->partial('telas/veiculos', ['variaveis'=>$this->telas]) ?>
    <?php echo $this->partial('telas/aplicacao/produtos', ['variaveis'=>$this->telas]) ?>
    <?php echo $this->partial('telas/aplicacao/marcas', ['variaveis'=>$this->telas]) ?>
    <?php echo $this->partial('telas/aplicacao/manutencao', ['variaveis'=>$this->telas]) ?>
    <?php echo $this->partial('telas/aplicacao/financeiro/lancamentos', ['variaveis'=>$this->telas]) ?>
   
</div>
