<div id="signupbox" style="display:non; margin-top:50px" class="mainbox col-lg-25">
    <div class="panel panel-info">
        <div class="panel-heading">
            <div class="panel-title">Quero fazer parte...</div>
        </div>  
        <div class="panel-body" >
            <form id="signupform" class="form-horizontal" role="form">

                <div id="signupalert" style="display:none" class="alert alert-danger">
                    <p>Erro:</p>
                    <span></span>
                </div>

                <div class="form-group">
                    <label for="firstname" class="col-lg-7 control-label">Nome</label>
                    <div class="col-lg-15">
                        <input type="text" class="form-control" name="firstname" placeholder="">
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="col-lg-7 control-label">E-mail</label>
                    <div class="col-lg-15">
                        <input type="text" class="form-control" name="email" placeholder="exemplo@gmail.com">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-lg-7 control-label">Senha</label>
                    <div class="col-lg-15">
                        <input type="password" class="form-control" name="passwd" placeholder="">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-lg-7 control-label">Repita a Senha</label>
                    <div class="col-lg-15">
                        <input type="password" class="form-control" name="passwd2" placeholder="">
                    </div>
                </div>

                <div class="form-group">
                    <!-- Button -->                                        
                    <div class="col-md-offset-3 col-lg-15">
                        <button id="btn-signup" type="button" class="btn btn-info"><i class="icon-hand-right"></i> Cadastrar</button>
                    </div>
                </div>

                <div style="padding-top:20px"  class="form-group">

                    <!--<div class="col-md-offset-3 col-lg-15">
                        <button id="btn-fbsignup" type="button" class="btn btn-primary"><i class="icon-facebook"></i>   Cadastre-se com o Facebook</button>
                    </div>-->
                    <div style="float:right; font-size: 85%; position: relative; top:-10px"><a id="signinlink" href="#" >Voltar à tela de Login <<<</a></div>                                           

                </div>         
            </form>
        </div>
    </div>
</div> 

