
<div class="janela col-xs-offset-2 col-sm-offset-2 col-md-offset-1 col-lg-offset-1 col-lg-8" style="display: none" data-title="Pessoas">
    <div class="divisao-janela">
        <form method="POST">
            <div class="modal-header">
                <button type="button" data-toggle="tooltip" data-placement="bottom" title="Fechar">
                    <i class="fa fa-close fa-1x"></i>
                </button>
                <h4 class="modal-title"><i class="fa fa-user fa-1x"></i> Gerenciamento de Pessoas</h4>
            </div>
            <div class="modal-body clearfix">
                <div class="col-lg-12" style="margin: 7px 0; max-height:400px; overflow:auto;">
                    <fieldset>
                        <legend>Pessoa:</legend>
                        <select id="pes_select" class="form-control" >
                            <option>Novo...</option>
                            <option>Novo1...</option>
                            <option>Novo2...</option>
                            <option>Novo3...</option>
                            <option>Novo4...</option>
                            <option>Novo5...</option>
                        </select>

                    </fieldset>
                </div>

                <div class="col-lg-12">
                    <fieldset>
                        <legend> Tipo: </legend>
                        <div class="form-group">
                            <span class="form-group ">
                                <input type="radio" id="pes_tipo_cli" name="pessoas_tipo" checked />
                                <label>Cliente</label>
                            </span>
                            <spam class="form-group ">
                                <input type="radio" id="pes_tipo_func" name="pessoas_tipo" />
                                <label>Funcionário</label>
                            </spam>
                        </div>
                    </fieldset>
                    <div class="col-lg-6 float-left" style="padding-left: 0">
                        
                        <fieldset>
                            <legend>Dados:</legend>
                            <div class="form-group col-lg-2">
                                <label>Código</label>
                                <input type="text" class="form-control" readonly />
                            </div>
                            <div class="form-group col-lg-10">
                                <label>Nome/Razão</label>
                                <input type="text" class="form-control" />
                            </div>
                            <div class="form-group col-lg-3">
                                <label>Doc. Número</label>
                                <input type="text" class="form-control" />
                            </div>
                            <div class="form-group col-lg-3">
                                <label>Doc. Tipo</label>
                                <select class="form-control"><option>CPF</option></select>
                            </div>
                            <div class="form-group col-lg-3">
                                <label>Data Nasc.</label>
                                <input type="text" id="pes_dta_nasc" class="form-control col-lg-12" readonly />
                            </div>
                            <div class="form-group col-lg-12">
                                <label>Observações</label>
                                <textarea class="form-control" ></textarea>
                            </div>
                        </fieldset>
                    </div>
                    <div class="col-lg-6">
                        <fieldset>
                            <legend> Contato: </legend>
                            <div class="form-group col-lg-6">
                                <label>Email</label>
                                <input type="text" class="form-control" />
                            </div>
                            <div class="form-group col-lg-12">
                                <label>Logradouro</label>
                                <input type="text" class="form-control" />
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Telefone 1</label>
                                <input type="text" class="form-control" />
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Telefone 2</label>
                                <input type="text" class="form-control" />
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Telefone 3</label>
                                <input type="text" class="form-control" />
                            </div>
                            <div class="form-group col-lg-12 text-right">
                                <input type="checkbox" id="pes_status" checked />
                                <label>Ativo</label>
                            </div>
                        </fieldset>
                    </div>
                </div>
                
                <div class="col-lg-6">
                    <fieldset>
                        <legend> Funcionário: </legend>
                        <div class="form-group col-lg-6">
                            <label>Cargo</label>
                            <input type="text" class="form-control" />
                        </div>
                        <div class="form-group col-lg-6">
                            <label>Salário</label>
                            <input type="text" class="form-control" />
                        </div>
                        <div class="form-group col-lg-12">
                                <label>Observações</label>
                                <textarea class="form-control" ></textarea>
                            </div>
                    </fieldset>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="text-center" data-toggle="tooltip" data-placement="bottom" title="Desfazer">
                    <i class="fa fa-undo fa-1x"></i>
                </button>
                <button class="text-center" data-toggle="tooltip" data-placement="bottom" title="Confirmar">
                    <i class="fa fa-check fa-1x"></i>
                </button>
            </div>
        </form>
    </div>
</div>
<!-- // Acompanhamento -->

<script>
    $("#pes_dta_nasc").datepicker();
</script>
