

<script type="text/javascript" src="/public/js/pessoas/veiculos.js"></script>

<div id="veic_janela" class="janela col-xs-offset-2 col-sm-offset-2 col-md-offset-1 col-lg-offset-1 col-lg-8" style="display: none" data-title="Veiculos">
    <div class="divisao-janela">
        <form method="POST" action="" id="veic_form">
            <div class="modal-header">
                <button type="button" data-toggle="tooltip" data-placement="bottom" title="Fechar">
                    <i class="fa fa-close "></i>
                </button>
                <h4 class="modal-title"><i class="fa fa-car "></i> Gerenciamento de Veículos</h4>
            </div>
            <div class="modal-body clearfix" style="padding-bottom: 5px;">
                
                <div id="veic_alertas" class="label label-default col-lg-12 hide"></div>

                <div class="col-lg-4">
                
                    <fieldset>
                        <legend>Pessoa:</legend>
                        <div class="col-lg-12" style="margin: 7px 0; max-height:400px; overflow:auto;">
                            <select id="veic_pes_select" class="form-control" name="pessoas_id" data-obrigatorio > <option>Selecione...</option> </select>
                        </div>
                    </fieldset>
                    <fieldset>
                        <legend>Veículo: </legend>
                        <div class="col-lg-4">
                            <label>Marca*</label>
                            <select id="veic_marca_select" class="form-control" name="marca_id" data-obrigatorio > <option>Selecione...</option> </select>
                        </div>
                        <div class="col-lg-5">
                            <label>Modelo*</label>
                            <input type="text" class="form-control" name="modelo" id="veic_modelo" data-obrigatorio />
                        </div>
                        <div class="col-lg-3" style="margin: 20px 0 5px 0; max-height:400px; overflow:auto;">
                            <button type="button" id="veic_add_marca" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Marca</button>
                        </div>
                        <div class="form-group col-lg-3">
                            <label>Placa*</label>
                            <input type="text" class="form-control" name="placa" id="veic_placa" data-obrigatorio />
                        </div>
                        <div class="form-group col-lg-4">
                            <label>Ano*</label>
                            <input type="text" class="form-control" name="ano" id="veic_ano" data-obrigatorio />
                        </div>
                        <div class="form-group col-lg-5">
                            <label>Cor*</label>
                            <input type="text" class="form-control" name="cor" id="veic_cor" data-obrigatorio />
                        </div>
                        <div>
                            <div class="form-group col-lg-12">
                                <label>Observações</label>
                                <textarea id="veic_obs" name="obs" class="form-control" ></textarea>
                            </div>
                        </div>
                        <div class="form-group col-lg-12 text-right">
                            <input type="checkbox" name="status" id="veic_status" checked />
                            <label>Ativo</label>
                        </div>
                    </fieldset>
                    <div class="col-lg-12 text-right" >
                        <button type="button" id="veic_desfazer" class="text-center btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Desfazer">
                            <i class="fa fa-undo "></i>
                        </button>
                        <button class="text-center btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Confirmar">
                            <i class="fa fa-check " style="color:#cc7a00"></i>
                        </button>
                    </div>
                    
                </div>
                <div class="col-lg-8">
                    <fieldset>
                        <legend>Últimos lançamentos:</legend>
                        <div class="col-lg-12" style="margin: 7px 0; max-height:400px; overflow:auto;">
                            <table id="veic_tabela" class="table table-bordered table-condensed">
                                <thead>
                                    <tr>
                                        <th class="col-lg-1">Modelo</th>
                                        <th class="col-lg-2">Marca</th>
                                        <th class="col-lg-1">Placa</th>
                                        <th class="col-lg-1">Ano</th>
                                        <th class="col-lg-2">Cor</th>
                                        <th class="col-lg-1">Status</th>
                                        <th>Obs</th>
                                        <th class="col-lg-1"><i class="fa fa-edit"></i></th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </fieldset>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="veic_modal_marca" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <form id="veic_modal_marca_form">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-close "></i></button>
                    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-edit "></i> Gerenciar marcas de veículos</h4>
                </div>
                <div class="modal-body clearfix">

                    <div id="veic_modal_marca_alertas" class="label label-default col-lg-12 hide"></div>

                    <div class="col-lg-12">
                        <fieldset>
                            <legend>Marcas: </legend>
                            <div class="form-group col-lg-12">
                                <label>Marca*</label>
                                <select id="veic_modal_marca_select" class="form-control" name="id" > <option>Nova...</option> </select>
                            </div>
                            <div class="form-group col-lg-12">
                                <label>Nome*</label>
                                <input type="text" class="form-control" name="nome" id="modal_veic_marca_nome" data-obrigatorio />
                            </div>
                            <div class="form-group col-lg-12 text-right">
                                <input type="checkbox" class="" name="status" id="modal_veic_marca_status" checked />
                                <label>Ativo</label>
                            </div>
                           
                        </fieldset>
                        
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="veic_modal_veic_marca_confirmar" class="text-center" data-toggle="tooltip" data-placement="bottom" title="Confirmar">
                        <i class="fa fa-check "></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="veic_modal_veic" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="veic_modal_form">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><i class="fa fa-close "></i></button>
                    <h4 class="modal-title" id="myModalLabel"><i class="fa fa-edit "></i> Alterar</h4>
                </div>
                <div class="modal-body clearfix">

                    <div id="veic_modal_alertas" class="label label-default col-lg-12 hide"></div>

                    <div class="col-lg-12">
                        <fieldset>
                            <legend>Veículo: </legend>
                            <div class="form-group  col-lg-6">
                                <label>Marca*</label>
                                <select id="modal_veic_marca_select" class="form-control" name="marca_id" data-obrigatorio > <option>Selecione...</option> </select>
                            </div>
                            <div class="form-group  col-lg-6">
                                <label>Modelo*</label>
                                <input type="text" class="form-control" name="modelo" id="modal_veic_modelo" data-obrigatorio />
                            </div>
                            <div class="form-group col-lg-3">
                                <label>Placa*</label>
                                <input type="text" class="form-control" name="placa" id="modal_veic_placa" data-obrigatorio />
                            </div>
                            <div class="form-group col-lg-4">
                                <label>Ano*</label>
                                <input type="text" class="form-control" name="ano" id="modal_veic_ano" data-obrigatorio />
                            </div>
                            <div class="form-group col-lg-5">
                                <label>Cor*</label>
                                <input type="text" class="form-control" name="cor" id="modal_veic_cor" data-obrigatorio />
                            </div>
                            <div class="form-group col-lg-12">
                                <label>Observações</label>
                                <textarea id="modal_veic_obs" name="obs" class="form-control" ></textarea>
                            </div>
                            <div class="form-group col-lg-12 text-right">
                                <input type="checkbox" name="status" id="modal_veic_status" checked />
                                <label>Ativo</label>
                            </div>

                            <input type="hidden" class="form-control" name="id" id="modal_veic_id" />
                        </fieldset>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="veic_modal_veic_confirmar" class="text-center" data-toggle="tooltip" data-placement="bottom" title="Confirmar">
                        <i class="fa fa-check "></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>